// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/common/json_api_client.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// JSONAPIClient is a mock of JSONAPIClient interface
type JSONAPIClient struct {
	ctrl     *gomock.Controller
	recorder *JSONAPIClientMockRecorder
}

// JSONAPIClientMockRecorder is the mock recorder for JSONAPIClient
type JSONAPIClientMockRecorder struct {
	mock *JSONAPIClient
}

// NewJSONAPIClient creates a new mock instance
func NewJSONAPIClient(ctrl *gomock.Controller) *JSONAPIClient {
	mock := &JSONAPIClient{ctrl: ctrl}
	mock.recorder = &JSONAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *JSONAPIClient) EXPECT() *JSONAPIClientMockRecorder {
	return m.recorder
}

// GetJSON mocks base method
func (m *JSONAPIClient) GetJSON(uri string) (map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetJSON", uri)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSON indicates an expected call of GetJSON
func (mr *JSONAPIClientMockRecorder) GetJSON(uri interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*JSONAPIClient)(nil).GetJSON), uri)
}
