builds:
  - binary: latest
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
release:
  draft: true
