language: go
go:
  - 1.9.x
before_install:
  - go get -u github.com/golang/lint/golint
  - which golint
before_script:
  - golint -set_exit_status
before_deploy:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - which rpm
  - gem install --no-ri --no-rdoc fpm
  - which fpm
deploy:
  provider: script
  script: rvm default do ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: PFRUWfVmEzxH9bb/ydao/eZHa4/b2XfcTt70fefB0tievWzVu9mX1Xfp/ztQcDunpgPDhGfUJ00J/xScmL/HX8xRk299Hj8SwIKuw+zOaXRkZQS2Ohz1xIdvNxSl08wil+W8DKBeI2pk0FhDAxRRLTqSmvBBtS80M9J9pbniRj36QUsZf80HA3QKm6rKT5MbYSwz/rfncLvbKNAd6lzgo9XmUIxlRad0kEzVPvXy4u0IjZ6dhnBQMUYO2BlcDbSh3s0onFXmTXEYyVsihhHdxwgh2uk9WxTE2ipUhAlcyAmOEAZq/13S5ka9mBngWzJ1gqk+lMDZm7SeshPUItJPYMwjJdNyFFO+b4RgKpP38pJY9D+Kp22Qhp4oJ/M9LzM2+P6+FmiESsKcfsySl8sVBnj0+O4kGOWByC3+VT296eDk1J9z7VxIQa4zFPxMJolCFKQJY7NCYei9O8C3xnp4P/lr5l1sNHO7p2dL9QHA24JtpN+uFVZQTG+I4L4EJKO/ChHcFg6czxQTjjZVJ3WhK84OMK3Ok1K2ljTtuJGJgv/+bR0/lCWJ6CFXFtj7MQUOoqSix+R7tjECX+8vkvbXtkVSpO3P5X52CmTFn8tHNOCU6UXz1QDBdKzanzoTmkaBnMTYHFgeQVzlFKO7Xv1Nt+eE0PCBdQhWyCG6VDU+uK4=
